//////////////////////////////////////////////////////////////////////////////////
// File:        DECODESTART.v
// Author:      Rowan Doherty
// Date:        April 2026
//
// Description: Two-stage pipelined popcount decoder for the start channel.
//              Converts a 360-bit thermometer code into a 9-bit binary count
//              of asserted taps.
//
//              Stage 1: the 360 input bits are split into 22 groups of 16
//                       bits plus one partial group of 8 bits. Each group is
//                       summed in parallel into a 5-bit partial result and
//                       registered.
//              Stage 2: the 23 partial results are summed into the final
//                       9-bit binary output and registered.
//
//              Pipelining the decoder keeps the combinational path short
//              enough to close timing at 300 MHz. Total latency is two
//              clock cycles; one new result is produced every cycle.
//
//              Popcount was chosen over leading-one detection because a
//              single-bit error (from a residual bubble or metastable tap)
//              changes the decoded value by only one count rather than
//              shifting it by an arbitrary amount.
//////////////////////////////////////////////////////////////////////////////////

`timescale 1ns / 1ps
`include "Defines.v"

module DECODESTART (
    input                      iCLK,
    input                      iRST,
    input  [`NUM_STAGES-1:0]   iTHERMOMETERSTART,
    output reg [`NUM_BITS-1:0] oBINSTART
);

    localparam NUM_GROUPS = 23;  // 22 full groups of 16 + 1 partial group of 8

    (* keep = "TRUE" *) reg [4:0] rPartial [0:NUM_GROUPS-1];

    integer i;

    // -------------------------------------------------------------------------
    // STAGE 1 - Sum each group in parallel
    //   Groups 0-21: 16 bits each (taps 0-351)
    //   Group 22:    8 bits only  (taps 352-359)
    // -------------------------------------------------------------------------
    always @(posedge iCLK) begin
        if (iRST) begin
            for (i = 0; i < NUM_GROUPS; i = i + 1)
                rPartial[i] <= 5'd0;
        end else begin
            rPartial[0]  <= iTHERMOMETERSTART[0]   + iTHERMOMETERSTART[1]   + iTHERMOMETERSTART[2]   + iTHERMOMETERSTART[3]   + iTHERMOMETERSTART[4]   + iTHERMOMETERSTART[5]   + iTHERMOMETERSTART[6]   + iTHERMOMETERSTART[7]   + iTHERMOMETERSTART[8]   + iTHERMOMETERSTART[9]   + iTHERMOMETERSTART[10]  + iTHERMOMETERSTART[11]  + iTHERMOMETERSTART[12]  + iTHERMOMETERSTART[13]  + iTHERMOMETERSTART[14]  + iTHERMOMETERSTART[15];
            rPartial[1]  <= iTHERMOMETERSTART[16]  + iTHERMOMETERSTART[17]  + iTHERMOMETERSTART[18]  + iTHERMOMETERSTART[19]  + iTHERMOMETERSTART[20]  + iTHERMOMETERSTART[21]  + iTHERMOMETERSTART[22]  + iTHERMOMETERSTART[23]  + iTHERMOMETERSTART[24]  + iTHERMOMETERSTART[25]  + iTHERMOMETERSTART[26]  + iTHERMOMETERSTART[27]  + iTHERMOMETERSTART[28]  + iTHERMOMETERSTART[29]  + iTHERMOMETERSTART[30]  + iTHERMOMETERSTART[31];
            rPartial[2]  <= iTHERMOMETERSTART[32]  + iTHERMOMETERSTART[33]  + iTHERMOMETERSTART[34]  + iTHERMOMETERSTART[35]  + iTHERMOMETERSTART[36]  + iTHERMOMETERSTART[37]  + iTHERMOMETERSTART[38]  + iTHERMOMETERSTART[39]  + iTHERMOMETERSTART[40]  + iTHERMOMETERSTART[41]  + iTHERMOMETERSTART[42]  + iTHERMOMETERSTART[43]  + iTHERMOMETERSTART[44]  + iTHERMOMETERSTART[45]  + iTHERMOMETERSTART[46]  + iTHERMOMETERSTART[47];
            rPartial[3]  <= iTHERMOMETERSTART[48]  + iTHERMOMETERSTART[49]  + iTHERMOMETERSTART[50]  + iTHERMOMETERSTART[51]  + iTHERMOMETERSTART[52]  + iTHERMOMETERSTART[53]  + iTHERMOMETERSTART[54]  + iTHERMOMETERSTART[55]  + iTHERMOMETERSTART[56]  + iTHERMOMETERSTART[57]  + iTHERMOMETERSTART[58]  + iTHERMOMETERSTART[59]  + iTHERMOMETERSTART[60]  + iTHERMOMETERSTART[61]  + iTHERMOMETERSTART[62]  + iTHERMOMETERSTART[63];
            rPartial[4]  <= iTHERMOMETERSTART[64]  + iTHERMOMETERSTART[65]  + iTHERMOMETERSTART[66]  + iTHERMOMETERSTART[67]  + iTHERMOMETERSTART[68]  + iTHERMOMETERSTART[69]  + iTHERMOMETERSTART[70]  + iTHERMOMETERSTART[71]  + iTHERMOMETERSTART[72]  + iTHERMOMETERSTART[73]  + iTHERMOMETERSTART[74]  + iTHERMOMETERSTART[75]  + iTHERMOMETERSTART[76]  + iTHERMOMETERSTART[77]  + iTHERMOMETERSTART[78]  + iTHERMOMETERSTART[79];
            rPartial[5]  <= iTHERMOMETERSTART[80]  + iTHERMOMETERSTART[81]  + iTHERMOMETERSTART[82]  + iTHERMOMETERSTART[83]  + iTHERMOMETERSTART[84]  + iTHERMOMETERSTART[85]  + iTHERMOMETERSTART[86]  + iTHERMOMETERSTART[87]  + iTHERMOMETERSTART[88]  + iTHERMOMETERSTART[89]  + iTHERMOMETERSTART[90]  + iTHERMOMETERSTART[91]  + iTHERMOMETERSTART[92]  + iTHERMOMETERSTART[93]  + iTHERMOMETERSTART[94]  + iTHERMOMETERSTART[95];
            rPartial[6]  <= iTHERMOMETERSTART[96]  + iTHERMOMETERSTART[97]  + iTHERMOMETERSTART[98]  + iTHERMOMETERSTART[99]  + iTHERMOMETERSTART[100] + iTHERMOMETERSTART[101] + iTHERMOMETERSTART[102] + iTHERMOMETERSTART[103] + iTHERMOMETERSTART[104] + iTHERMOMETERSTART[105] + iTHERMOMETERSTART[106] + iTHERMOMETERSTART[107] + iTHERMOMETERSTART[108] + iTHERMOMETERSTART[109] + iTHERMOMETERSTART[110] + iTHERMOMETERSTART[111];
            rPartial[7]  <= iTHERMOMETERSTART[112] + iTHERMOMETERSTART[113] + iTHERMOMETERSTART[114] + iTHERMOMETERSTART[115] + iTHERMOMETERSTART[116] + iTHERMOMETERSTART[117] + iTHERMOMETERSTART[118] + iTHERMOMETERSTART[119] + iTHERMOMETERSTART[120] + iTHERMOMETERSTART[121] + iTHERMOMETERSTART[122] + iTHERMOMETERSTART[123] + iTHERMOMETERSTART[124] + iTHERMOMETERSTART[125] + iTHERMOMETERSTART[126] + iTHERMOMETERSTART[127];
            rPartial[8]  <= iTHERMOMETERSTART[128] + iTHERMOMETERSTART[129] + iTHERMOMETERSTART[130] + iTHERMOMETERSTART[131] + iTHERMOMETERSTART[132] + iTHERMOMETERSTART[133] + iTHERMOMETERSTART[134] + iTHERMOMETERSTART[135] + iTHERMOMETERSTART[136] + iTHERMOMETERSTART[137] + iTHERMOMETERSTART[138] + iTHERMOMETERSTART[139] + iTHERMOMETERSTART[140] + iTHERMOMETERSTART[141] + iTHERMOMETERSTART[142] + iTHERMOMETERSTART[143];
            rPartial[9]  <= iTHERMOMETERSTART[144] + iTHERMOMETERSTART[145] + iTHERMOMETERSTART[146] + iTHERMOMETERSTART[147] + iTHERMOMETERSTART[148] + iTHERMOMETERSTART[149] + iTHERMOMETERSTART[150] + iTHERMOMETERSTART[151] + iTHERMOMETERSTART[152] + iTHERMOMETERSTART[153] + iTHERMOMETERSTART[154] + iTHERMOMETERSTART[155] + iTHERMOMETERSTART[156] + iTHERMOMETERSTART[157] + iTHERMOMETERSTART[158] + iTHERMOMETERSTART[159];
            rPartial[10] <= iTHERMOMETERSTART[160] + iTHERMOMETERSTART[161] + iTHERMOMETERSTART[162] + iTHERMOMETERSTART[163] + iTHERMOMETERSTART[164] + iTHERMOMETERSTART[165] + iTHERMOMETERSTART[166] + iTHERMOMETERSTART[167] + iTHERMOMETERSTART[168] + iTHERMOMETERSTART[169] + iTHERMOMETERSTART[170] + iTHERMOMETERSTART[171] + iTHERMOMETERSTART[172] + iTHERMOMETERSTART[173] + iTHERMOMETERSTART[174] + iTHERMOMETERSTART[175];
            rPartial[11] <= iTHERMOMETERSTART[176] + iTHERMOMETERSTART[177] + iTHERMOMETERSTART[178] + iTHERMOMETERSTART[179] + iTHERMOMETERSTART[180] + iTHERMOMETERSTART[181] + iTHERMOMETERSTART[182] + iTHERMOMETERSTART[183] + iTHERMOMETERSTART[184] + iTHERMOMETERSTART[185] + iTHERMOMETERSTART[186] + iTHERMOMETERSTART[187] + iTHERMOMETERSTART[188] + iTHERMOMETERSTART[189] + iTHERMOMETERSTART[190] + iTHERMOMETERSTART[191];
            rPartial[12] <= iTHERMOMETERSTART[192] + iTHERMOMETERSTART[193] + iTHERMOMETERSTART[194] + iTHERMOMETERSTART[195] + iTHERMOMETERSTART[196] + iTHERMOMETERSTART[197] + iTHERMOMETERSTART[198] + iTHERMOMETERSTART[199] + iTHERMOMETERSTART[200] + iTHERMOMETERSTART[201] + iTHERMOMETERSTART[202] + iTHERMOMETERSTART[203] + iTHERMOMETERSTART[204] + iTHERMOMETERSTART[205] + iTHERMOMETERSTART[206] + iTHERMOMETERSTART[207];
            rPartial[13] <= iTHERMOMETERSTART[208] + iTHERMOMETERSTART[209] + iTHERMOMETERSTART[210] + iTHERMOMETERSTART[211] + iTHERMOMETERSTART[212] + iTHERMOMETERSTART[213] + iTHERMOMETERSTART[214] + iTHERMOMETERSTART[215] + iTHERMOMETERSTART[216] + iTHERMOMETERSTART[217] + iTHERMOMETERSTART[218] + iTHERMOMETERSTART[219] + iTHERMOMETERSTART[220] + iTHERMOMETERSTART[221] + iTHERMOMETERSTART[222] + iTHERMOMETERSTART[223];
            rPartial[14] <= iTHERMOMETERSTART[224] + iTHERMOMETERSTART[225] + iTHERMOMETERSTART[226] + iTHERMOMETERSTART[227] + iTHERMOMETERSTART[228] + iTHERMOMETERSTART[229] + iTHERMOMETERSTART[230] + iTHERMOMETERSTART[231] + iTHERMOMETERSTART[232] + iTHERMOMETERSTART[233] + iTHERMOMETERSTART[234] + iTHERMOMETERSTART[235] + iTHERMOMETERSTART[236] + iTHERMOMETERSTART[237] + iTHERMOMETERSTART[238] + iTHERMOMETERSTART[239];
            rPartial[15] <= iTHERMOMETERSTART[240] + iTHERMOMETERSTART[241] + iTHERMOMETERSTART[242] + iTHERMOMETERSTART[243] + iTHERMOMETERSTART[244] + iTHERMOMETERSTART[245] + iTHERMOMETERSTART[246] + iTHERMOMETERSTART[247] + iTHERMOMETERSTART[248] + iTHERMOMETERSTART[249] + iTHERMOMETERSTART[250] + iTHERMOMETERSTART[251] + iTHERMOMETERSTART[252] + iTHERMOMETERSTART[253] + iTHERMOMETERSTART[254] + iTHERMOMETERSTART[255];
            rPartial[16] <= iTHERMOMETERSTART[256] + iTHERMOMETERSTART[257] + iTHERMOMETERSTART[258] + iTHERMOMETERSTART[259] + iTHERMOMETERSTART[260] + iTHERMOMETERSTART[261] + iTHERMOMETERSTART[262] + iTHERMOMETERSTART[263] + iTHERMOMETERSTART[264] + iTHERMOMETERSTART[265] + iTHERMOMETERSTART[266] + iTHERMOMETERSTART[267] + iTHERMOMETERSTART[268] + iTHERMOMETERSTART[269] + iTHERMOMETERSTART[270] + iTHERMOMETERSTART[271];
            rPartial[17] <= iTHERMOMETERSTART[272] + iTHERMOMETERSTART[273] + iTHERMOMETERSTART[274] + iTHERMOMETERSTART[275] + iTHERMOMETERSTART[276] + iTHERMOMETERSTART[277] + iTHERMOMETERSTART[278] + iTHERMOMETERSTART[279] + iTHERMOMETERSTART[280] + iTHERMOMETERSTART[281] + iTHERMOMETERSTART[282] + iTHERMOMETERSTART[283] + iTHERMOMETERSTART[284] + iTHERMOMETERSTART[285] + iTHERMOMETERSTART[286] + iTHERMOMETERSTART[287];
            rPartial[18] <= iTHERMOMETERSTART[288] + iTHERMOMETERSTART[289] + iTHERMOMETERSTART[290] + iTHERMOMETERSTART[291] + iTHERMOMETERSTART[292] + iTHERMOMETERSTART[293] + iTHERMOMETERSTART[294] + iTHERMOMETERSTART[295] + iTHERMOMETERSTART[296] + iTHERMOMETERSTART[297] + iTHERMOMETERSTART[298] + iTHERMOMETERSTART[299] + iTHERMOMETERSTART[300] + iTHERMOMETERSTART[301] + iTHERMOMETERSTART[302] + iTHERMOMETERSTART[303];
            rPartial[19] <= iTHERMOMETERSTART[304] + iTHERMOMETERSTART[305] + iTHERMOMETERSTART[306] + iTHERMOMETERSTART[307] + iTHERMOMETERSTART[308] + iTHERMOMETERSTART[309] + iTHERMOMETERSTART[310] + iTHERMOMETERSTART[311] + iTHERMOMETERSTART[312] + iTHERMOMETERSTART[313] + iTHERMOMETERSTART[314] + iTHERMOMETERSTART[315] + iTHERMOMETERSTART[316] + iTHERMOMETERSTART[317] + iTHERMOMETERSTART[318] + iTHERMOMETERSTART[319];
            rPartial[20] <= iTHERMOMETERSTART[320] + iTHERMOMETERSTART[321] + iTHERMOMETERSTART[322] + iTHERMOMETERSTART[323] + iTHERMOMETERSTART[324] + iTHERMOMETERSTART[325] + iTHERMOMETERSTART[326] + iTHERMOMETERSTART[327] + iTHERMOMETERSTART[328] + iTHERMOMETERSTART[329] + iTHERMOMETERSTART[330] + iTHERMOMETERSTART[331] + iTHERMOMETERSTART[332] + iTHERMOMETERSTART[333] + iTHERMOMETERSTART[334] + iTHERMOMETERSTART[335];
            rPartial[21] <= iTHERMOMETERSTART[336] + iTHERMOMETERSTART[337] + iTHERMOMETERSTART[338] + iTHERMOMETERSTART[339] + iTHERMOMETERSTART[340] + iTHERMOMETERSTART[341] + iTHERMOMETERSTART[342] + iTHERMOMETERSTART[343] + iTHERMOMETERSTART[344] + iTHERMOMETERSTART[345] + iTHERMOMETERSTART[346] + iTHERMOMETERSTART[347] + iTHERMOMETERSTART[348] + iTHERMOMETERSTART[349] + iTHERMOMETERSTART[350] + iTHERMOMETERSTART[351];
            // Partial group - only 8 taps remaining (352-359)
            rPartial[22] <= iTHERMOMETERSTART[352] + iTHERMOMETERSTART[353] + iTHERMOMETERSTART[354] + iTHERMOMETERSTART[355] + iTHERMOMETERSTART[356] + iTHERMOMETERSTART[357] + iTHERMOMETERSTART[358] + iTHERMOMETERSTART[359];
        end
    end

    // -------------------------------------------------------------------------
    // STAGE 2 - Sum all 23 partial results
    // -------------------------------------------------------------------------
    always @(posedge iCLK) begin
        if (iRST) begin
            oBINSTART <= 0;
        end else begin
            oBINSTART <= rPartial[0]  + rPartial[1]  + rPartial[2]  + rPartial[3]  +
                         rPartial[4]  + rPartial[5]  + rPartial[6]  + rPartial[7]  +
                         rPartial[8]  + rPartial[9]  + rPartial[10] + rPartial[11] +
                         rPartial[12] + rPartial[13] + rPartial[14] + rPartial[15] +
                         rPartial[16] + rPartial[17] + rPartial[18] + rPartial[19] +
                         rPartial[20] + rPartial[21] + rPartial[22];
        end
    end

endmodule
