//////////////////////////////////////////////////////////////////////////////////
// File:        DECODESTOP.v
// Author:      Rowan Doherty
// Date:        April 2026
//
// Description: Two-stage pipelined popcount decoder for the stop channel.
//              Identical in structure to DECODESTART but operates on the stop
//              event's thermometer code. Converts a 360-bit thermometer code
//              into a 9-bit binary count of asserted taps.
//
//              Stage 1: the 360 input bits are split into 22 groups of 16
//                       bits plus one partial group of 8 bits. Each group is
//                       summed in parallel into a 5-bit partial result and
//                       registered.
//              Stage 2: the 23 partial results are summed into the final
//                       9-bit binary output and registered.
//
//              Pipelining the decoder keeps the combinational path short
//              enough to close timing at 300 MHz. Total latency is two
//              clock cycles; one new result is produced every cycle.
//
//              Popcount was chosen over leading-one detection because a
//              single-bit error (from a residual bubble or metastable tap)
//              changes the decoded value by only one count rather than
//              shifting it by an arbitrary amount.
//////////////////////////////////////////////////////////////////////////////////

`timescale 1ns / 1ps
`include "Defines.v"

module DECODESTOP (
    input                      iCLK,
    input                      iRST,
    input  [`NUM_STAGES-1:0]   iTHERMOMETERSTOP,
    output reg [`NUM_BITS-1:0] oBINSTOP
);

    localparam NUM_GROUPS = 23;  // 22 full groups of 16 + 1 partial group of 8

    (* keep = "TRUE" *) reg [4:0] rPartial [0:NUM_GROUPS-1];

    integer i;

    // -------------------------------------------------------------------------
    // STAGE 1 - Sum each group in parallel
    //   Groups 0-21: 16 bits each (taps 0-351)
    //   Group 22:    8 bits only  (taps 352-359)
    // -------------------------------------------------------------------------
    always @(posedge iCLK) begin
        if (iRST) begin
            for (i = 0; i < NUM_GROUPS; i = i + 1)
                rPartial[i] <= 5'd0;
        end else begin
            rPartial[0]  <= iTHERMOMETERSTOP[0]   + iTHERMOMETERSTOP[1]   + iTHERMOMETERSTOP[2]   + iTHERMOMETERSTOP[3]   + iTHERMOMETERSTOP[4]   + iTHERMOMETERSTOP[5]   + iTHERMOMETERSTOP[6]   + iTHERMOMETERSTOP[7]   + iTHERMOMETERSTOP[8]   + iTHERMOMETERSTOP[9]   + iTHERMOMETERSTOP[10]  + iTHERMOMETERSTOP[11]  + iTHERMOMETERSTOP[12]  + iTHERMOMETERSTOP[13]  + iTHERMOMETERSTOP[14]  + iTHERMOMETERSTOP[15];
            rPartial[1]  <= iTHERMOMETERSTOP[16]  + iTHERMOMETERSTOP[17]  + iTHERMOMETERSTOP[18]  + iTHERMOMETERSTOP[19]  + iTHERMOMETERSTOP[20]  + iTHERMOMETERSTOP[21]  + iTHERMOMETERSTOP[22]  + iTHERMOMETERSTOP[23]  + iTHERMOMETERSTOP[24]  + iTHERMOMETERSTOP[25]  + iTHERMOMETERSTOP[26]  + iTHERMOMETERSTOP[27]  + iTHERMOMETERSTOP[28]  + iTHERMOMETERSTOP[29]  + iTHERMOMETERSTOP[30]  + iTHERMOMETERSTOP[31];
            rPartial[2]  <= iTHERMOMETERSTOP[32]  + iTHERMOMETERSTOP[33]  + iTHERMOMETERSTOP[34]  + iTHERMOMETERSTOP[35]  + iTHERMOMETERSTOP[36]  + iTHERMOMETERSTOP[37]  + iTHERMOMETERSTOP[38]  + iTHERMOMETERSTOP[39]  + iTHERMOMETERSTOP[40]  + iTHERMOMETERSTOP[41]  + iTHERMOMETERSTOP[42]  + iTHERMOMETERSTOP[43]  + iTHERMOMETERSTOP[44]  + iTHERMOMETERSTOP[45]  + iTHERMOMETERSTOP[46]  + iTHERMOMETERSTOP[47];
            rPartial[3]  <= iTHERMOMETERSTOP[48]  + iTHERMOMETERSTOP[49]  + iTHERMOMETERSTOP[50]  + iTHERMOMETERSTOP[51]  + iTHERMOMETERSTOP[52]  + iTHERMOMETERSTOP[53]  + iTHERMOMETERSTOP[54]  + iTHERMOMETERSTOP[55]  + iTHERMOMETERSTOP[56]  + iTHERMOMETERSTOP[57]  + iTHERMOMETERSTOP[58]  + iTHERMOMETERSTOP[59]  + iTHERMOMETERSTOP[60]  + iTHERMOMETERSTOP[61]  + iTHERMOMETERSTOP[62]  + iTHERMOMETERSTOP[63];
            rPartial[4]  <= iTHERMOMETERSTOP[64]  + iTHERMOMETERSTOP[65]  + iTHERMOMETERSTOP[66]  + iTHERMOMETERSTOP[67]  + iTHERMOMETERSTOP[68]  + iTHERMOMETERSTOP[69]  + iTHERMOMETERSTOP[70]  + iTHERMOMETERSTOP[71]  + iTHERMOMETERSTOP[72]  + iTHERMOMETERSTOP[73]  + iTHERMOMETERSTOP[74]  + iTHERMOMETERSTOP[75]  + iTHERMOMETERSTOP[76]  + iTHERMOMETERSTOP[77]  + iTHERMOMETERSTOP[78]  + iTHERMOMETERSTOP[79];
            rPartial[5]  <= iTHERMOMETERSTOP[80]  + iTHERMOMETERSTOP[81]  + iTHERMOMETERSTOP[82]  + iTHERMOMETERSTOP[83]  + iTHERMOMETERSTOP[84]  + iTHERMOMETERSTOP[85]  + iTHERMOMETERSTOP[86]  + iTHERMOMETERSTOP[87]  + iTHERMOMETERSTOP[88]  + iTHERMOMETERSTOP[89]  + iTHERMOMETERSTOP[90]  + iTHERMOMETERSTOP[91]  + iTHERMOMETERSTOP[92]  + iTHERMOMETERSTOP[93]  + iTHERMOMETERSTOP[94]  + iTHERMOMETERSTOP[95];
            rPartial[6]  <= iTHERMOMETERSTOP[96]  + iTHERMOMETERSTOP[97]  + iTHERMOMETERSTOP[98]  + iTHERMOMETERSTOP[99]  + iTHERMOMETERSTOP[100] + iTHERMOMETERSTOP[101] + iTHERMOMETERSTOP[102] + iTHERMOMETERSTOP[103] + iTHERMOMETERSTOP[104] + iTHERMOMETERSTOP[105] + iTHERMOMETERSTOP[106] + iTHERMOMETERSTOP[107] + iTHERMOMETERSTOP[108] + iTHERMOMETERSTOP[109] + iTHERMOMETERSTOP[110] + iTHERMOMETERSTOP[111];
            rPartial[7]  <= iTHERMOMETERSTOP[112] + iTHERMOMETERSTOP[113] + iTHERMOMETERSTOP[114] + iTHERMOMETERSTOP[115] + iTHERMOMETERSTOP[116] + iTHERMOMETERSTOP[117] + iTHERMOMETERSTOP[118] + iTHERMOMETERSTOP[119] + iTHERMOMETERSTOP[120] + iTHERMOMETERSTOP[121] + iTHERMOMETERSTOP[122] + iTHERMOMETERSTOP[123] + iTHERMOMETERSTOP[124] + iTHERMOMETERSTOP[125] + iTHERMOMETERSTOP[126] + iTHERMOMETERSTOP[127];
            rPartial[8]  <= iTHERMOMETERSTOP[128] + iTHERMOMETERSTOP[129] + iTHERMOMETERSTOP[130] + iTHERMOMETERSTOP[131] + iTHERMOMETERSTOP[132] + iTHERMOMETERSTOP[133] + iTHERMOMETERSTOP[134] + iTHERMOMETERSTOP[135] + iTHERMOMETERSTOP[136] + iTHERMOMETERSTOP[137] + iTHERMOMETERSTOP[138] + iTHERMOMETERSTOP[139] + iTHERMOMETERSTOP[140] + iTHERMOMETERSTOP[141] + iTHERMOMETERSTOP[142] + iTHERMOMETERSTOP[143];
            rPartial[9]  <= iTHERMOMETERSTOP[144] + iTHERMOMETERSTOP[145] + iTHERMOMETERSTOP[146] + iTHERMOMETERSTOP[147] + iTHERMOMETERSTOP[148] + iTHERMOMETERSTOP[149] + iTHERMOMETERSTOP[150] + iTHERMOMETERSTOP[151] + iTHERMOMETERSTOP[152] + iTHERMOMETERSTOP[153] + iTHERMOMETERSTOP[154] + iTHERMOMETERSTOP[155] + iTHERMOMETERSTOP[156] + iTHERMOMETERSTOP[157] + iTHERMOMETERSTOP[158] + iTHERMOMETERSTOP[159];
            rPartial[10] <= iTHERMOMETERSTOP[160] + iTHERMOMETERSTOP[161] + iTHERMOMETERSTOP[162] + iTHERMOMETERSTOP[163] + iTHERMOMETERSTOP[164] + iTHERMOMETERSTOP[165] + iTHERMOMETERSTOP[166] + iTHERMOMETERSTOP[167] + iTHERMOMETERSTOP[168] + iTHERMOMETERSTOP[169] + iTHERMOMETERSTOP[170] + iTHERMOMETERSTOP[171] + iTHERMOMETERSTOP[172] + iTHERMOMETERSTOP[173] + iTHERMOMETERSTOP[174] + iTHERMOMETERSTOP[175];
            rPartial[11] <= iTHERMOMETERSTOP[176] + iTHERMOMETERSTOP[177] + iTHERMOMETERSTOP[178] + iTHERMOMETERSTOP[179] + iTHERMOMETERSTOP[180] + iTHERMOMETERSTOP[181] + iTHERMOMETERSTOP[182] + iTHERMOMETERSTOP[183] + iTHERMOMETERSTOP[184] + iTHERMOMETERSTOP[185] + iTHERMOMETERSTOP[186] + iTHERMOMETERSTOP[187] + iTHERMOMETERSTOP[188] + iTHERMOMETERSTOP[189] + iTHERMOMETERSTOP[190] + iTHERMOMETERSTOP[191];
            rPartial[12] <= iTHERMOMETERSTOP[192] + iTHERMOMETERSTOP[193] + iTHERMOMETERSTOP[194] + iTHERMOMETERSTOP[195] + iTHERMOMETERSTOP[196] + iTHERMOMETERSTOP[197] + iTHERMOMETERSTOP[198] + iTHERMOMETERSTOP[199] + iTHERMOMETERSTOP[200] + iTHERMOMETERSTOP[201] + iTHERMOMETERSTOP[202] + iTHERMOMETERSTOP[203] + iTHERMOMETERSTOP[204] + iTHERMOMETERSTOP[205] + iTHERMOMETERSTOP[206] + iTHERMOMETERSTOP[207];
            rPartial[13] <= iTHERMOMETERSTOP[208] + iTHERMOMETERSTOP[209] + iTHERMOMETERSTOP[210] + iTHERMOMETERSTOP[211] + iTHERMOMETERSTOP[212] + iTHERMOMETERSTOP[213] + iTHERMOMETERSTOP[214] + iTHERMOMETERSTOP[215] + iTHERMOMETERSTOP[216] + iTHERMOMETERSTOP[217] + iTHERMOMETERSTOP[218] + iTHERMOMETERSTOP[219] + iTHERMOMETERSTOP[220] + iTHERMOMETERSTOP[221] + iTHERMOMETERSTOP[222] + iTHERMOMETERSTOP[223];
            rPartial[14] <= iTHERMOMETERSTOP[224] + iTHERMOMETERSTOP[225] + iTHERMOMETERSTOP[226] + iTHERMOMETERSTOP[227] + iTHERMOMETERSTOP[228] + iTHERMOMETERSTOP[229] + iTHERMOMETERSTOP[230] + iTHERMOMETERSTOP[231] + iTHERMOMETERSTOP[232] + iTHERMOMETERSTOP[233] + iTHERMOMETERSTOP[234] + iTHERMOMETERSTOP[235] + iTHERMOMETERSTOP[236] + iTHERMOMETERSTOP[237] + iTHERMOMETERSTOP[238] + iTHERMOMETERSTOP[239];
            rPartial[15] <= iTHERMOMETERSTOP[240] + iTHERMOMETERSTOP[241] + iTHERMOMETERSTOP[242] + iTHERMOMETERSTOP[243] + iTHERMOMETERSTOP[244] + iTHERMOMETERSTOP[245] + iTHERMOMETERSTOP[246] + iTHERMOMETERSTOP[247] + iTHERMOMETERSTOP[248] + iTHERMOMETERSTOP[249] + iTHERMOMETERSTOP[250] + iTHERMOMETERSTOP[251] + iTHERMOMETERSTOP[252] + iTHERMOMETERSTOP[253] + iTHERMOMETERSTOP[254] + iTHERMOMETERSTOP[255];
            rPartial[16] <= iTHERMOMETERSTOP[256] + iTHERMOMETERSTOP[257] + iTHERMOMETERSTOP[258] + iTHERMOMETERSTOP[259] + iTHERMOMETERSTOP[260] + iTHERMOMETERSTOP[261] + iTHERMOMETERSTOP[262] + iTHERMOMETERSTOP[263] + iTHERMOMETERSTOP[264] + iTHERMOMETERSTOP[265] + iTHERMOMETERSTOP[266] + iTHERMOMETERSTOP[267] + iTHERMOMETERSTOP[268] + iTHERMOMETERSTOP[269] + iTHERMOMETERSTOP[270] + iTHERMOMETERSTOP[271];
            rPartial[17] <= iTHERMOMETERSTOP[272] + iTHERMOMETERSTOP[273] + iTHERMOMETERSTOP[274] + iTHERMOMETERSTOP[275] + iTHERMOMETERSTOP[276] + iTHERMOMETERSTOP[277] + iTHERMOMETERSTOP[278] + iTHERMOMETERSTOP[279] + iTHERMOMETERSTOP[280] + iTHERMOMETERSTOP[281] + iTHERMOMETERSTOP[282] + iTHERMOMETERSTOP[283] + iTHERMOMETERSTOP[284] + iTHERMOMETERSTOP[285] + iTHERMOMETERSTOP[286] + iTHERMOMETERSTOP[287];
            rPartial[18] <= iTHERMOMETERSTOP[288] + iTHERMOMETERSTOP[289] + iTHERMOMETERSTOP[290] + iTHERMOMETERSTOP[291] + iTHERMOMETERSTOP[292] + iTHERMOMETERSTOP[293] + iTHERMOMETERSTOP[294] + iTHERMOMETERSTOP[295] + iTHERMOMETERSTOP[296] + iTHERMOMETERSTOP[297] + iTHERMOMETERSTOP[298] + iTHERMOMETERSTOP[299] + iTHERMOMETERSTOP[300] + iTHERMOMETERSTOP[301] + iTHERMOMETERSTOP[302] + iTHERMOMETERSTOP[303];
            rPartial[19] <= iTHERMOMETERSTOP[304] + iTHERMOMETERSTOP[305] + iTHERMOMETERSTOP[306] + iTHERMOMETERSTOP[307] + iTHERMOMETERSTOP[308] + iTHERMOMETERSTOP[309] + iTHERMOMETERSTOP[310] + iTHERMOMETERSTOP[311] + iTHERMOMETERSTOP[312] + iTHERMOMETERSTOP[313] + iTHERMOMETERSTOP[314] + iTHERMOMETERSTOP[315] + iTHERMOMETERSTOP[316] + iTHERMOMETERSTOP[317] + iTHERMOMETERSTOP[318] + iTHERMOMETERSTOP[319];
            rPartial[20] <= iTHERMOMETERSTOP[320] + iTHERMOMETERSTOP[321] + iTHERMOMETERSTOP[322] + iTHERMOMETERSTOP[323] + iTHERMOMETERSTOP[324] + iTHERMOMETERSTOP[325] + iTHERMOMETERSTOP[326] + iTHERMOMETERSTOP[327] + iTHERMOMETERSTOP[328] + iTHERMOMETERSTOP[329] + iTHERMOMETERSTOP[330] + iTHERMOMETERSTOP[331] + iTHERMOMETERSTOP[332] + iTHERMOMETERSTOP[333] + iTHERMOMETERSTOP[334] + iTHERMOMETERSTOP[335];
            rPartial[21] <= iTHERMOMETERSTOP[336] + iTHERMOMETERSTOP[337] + iTHERMOMETERSTOP[338] + iTHERMOMETERSTOP[339] + iTHERMOMETERSTOP[340] + iTHERMOMETERSTOP[341] + iTHERMOMETERSTOP[342] + iTHERMOMETERSTOP[343] + iTHERMOMETERSTOP[344] + iTHERMOMETERSTOP[345] + iTHERMOMETERSTOP[346] + iTHERMOMETERSTOP[347] + iTHERMOMETERSTOP[348] + iTHERMOMETERSTOP[349] + iTHERMOMETERSTOP[350] + iTHERMOMETERSTOP[351];
            // Partial group - only 8 taps remaining (352-359)
            rPartial[22] <= iTHERMOMETERSTOP[352] + iTHERMOMETERSTOP[353] + iTHERMOMETERSTOP[354] + iTHERMOMETERSTOP[355] + iTHERMOMETERSTOP[356] + iTHERMOMETERSTOP[357] + iTHERMOMETERSTOP[358] + iTHERMOMETERSTOP[359];
        end
    end

    // -------------------------------------------------------------------------
    // STAGE 2 - Sum all 23 partial results
    // -------------------------------------------------------------------------
    always @(posedge iCLK) begin
        if (iRST) begin
            oBINSTOP <= 0;
        end else begin
            oBINSTOP <= rPartial[0]  + rPartial[1]  + rPartial[2]  + rPartial[3]  +
                        rPartial[4]  + rPartial[5]  + rPartial[6]  + rPartial[7]  +
                        rPartial[8]  + rPartial[9]  + rPartial[10] + rPartial[11] +
                        rPartial[12] + rPartial[13] + rPartial[14] + rPartial[15] +
                        rPartial[16] + rPartial[17] + rPartial[18] + rPartial[19] +
                        rPartial[20] + rPartial[21] + rPartial[22];
        end
    end

endmodule
